version: '3.8'
services:
  nginx:
    container_name: nginx
    network_mode: host
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - APP_URL=http://${APP_HOST}:${APP_PORT}
